"""
modules/db.py
─────────────────────────────────────────────────────────────
Módulo de acesso ao banco de dados Oracle.
Responsável por:
  - Gerenciar a conexão com o Oracle via python-oracledb (thin mode)
  - Criar as tabelas do projeto (DDL)
  - Fornecer funções CRUD para os módulos da aplicação
─────────────────────────────────────────────────────────────
"""

import os
import oracledb
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

# ─────────────────────────────────────────────────────────────
# CONFIGURAÇÃO DE CONEXÃO
# ─────────────────────────────────────────────────────────────

def get_connection():
    """
    Retorna uma conexão ativa com o banco Oracle.
    Usa o modo 'thin' do oracledb (não precisa do Oracle Client instalado).
    """
    conn = oracledb.connect(
        user=os.getenv("RM567477"),
        password=os.getenv("261298"),
        dsn=os.getenv("oracle.fiap.com.br:1521/ORCL")
    )
    return conn


# ─────────────────────────────────────────────────────────────
# DDL — CRIAÇÃO DAS TABELAS
# ─────────────────────────────────────────────────────────────

DDL_VISITANTES = """
CREATE TABLE visitantes (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR2(100),
    perfil      VARCHAR2(50),       -- estudante, turista, pesquisador, profissional
    idade_faixa VARCHAR2(20),       -- jovem, adulto, idoso
    criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

DDL_INTERACOES = """
CREATE TABLE interacoes (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitante_id    NUMBER REFERENCES visitantes(id),
    tipo_acao       VARCHAR2(50),   -- chatbot, imagem, menu, busca
    categoria       VARCHAR2(50),   -- arte, ciencia, historia, tecnologia
    duracao_seg     NUMBER(5),      -- tempo de interação em segundos
    satisfacao      NUMBER(1),      -- avaliação 1-5
    registrado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

DDL_LOGS_SISTEMA = """
CREATE TABLE logs_sistema (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo      VARCHAR2(50),       -- vision, chatbot, classificador
    evento      VARCHAR2(200),
    nivel       VARCHAR2(10),       -- INFO, WARN, ERROR
    registrado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""


def criar_tabelas():
    """
    Cria todas as tabelas necessárias no banco Oracle.
    Ignora erro ORA-00955 (tabela já existe).
    """
    tabelas = {
        "visitantes": DDL_VISITANTES,
        "interacoes": DDL_INTERACOES,
        "logs_sistema": DDL_LOGS_SISTEMA,
    }

    conn = get_connection()
    cursor = conn.cursor()

    for nome, ddl in tabelas.items():
        try:
            cursor.execute(ddl)
            print(f"[DB] Tabela '{nome}' criada com sucesso.")
        except oracledb.DatabaseError as e:
            error, = e.args
            if error.code == 955:  # ORA-00955: name is already used
                print(f"[DB] Tabela '{nome}' já existe, ignorando.")
            else:
                raise

    conn.commit()
    cursor.close()
    conn.close()


# ─────────────────────────────────────────────────────────────
# CRUD — VISITANTES
# ─────────────────────────────────────────────────────────────

def inserir_visitante(nome: str, perfil: str, idade_faixa: str) -> int:
    """Insere um novo visitante e retorna o ID gerado."""
    sql = """
        INSERT INTO visitantes (nome, perfil, idade_faixa)
        VALUES (:nome, :perfil, :idade_faixa)
        RETURNING id INTO :novo_id
    """
    conn = get_connection()
    cursor = conn.cursor()

    novo_id = cursor.var(oracledb.NUMBER)
    cursor.execute(sql, {"nome": nome, "perfil": perfil,
                         "idade_faixa": idade_faixa, "novo_id": novo_id})
    conn.commit()
    cursor.close()
    conn.close()

    return int(novo_id.getvalue()[0])


def listar_visitantes(limit: int = 100) -> list[dict]:
    """Retorna os últimos N visitantes registrados."""
    sql = """
        SELECT id, nome, perfil, idade_faixa, criado_em
        FROM visitantes
        ORDER BY criado_em DESC
        FETCH FIRST :limit ROWS ONLY
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(sql, {"limit": limit})
    colunas = [col[0].lower() for col in cursor.description]
    rows = [dict(zip(colunas, row)) for row in cursor.fetchall()]
    cursor.close()
    conn.close()
    return rows


# ─────────────────────────────────────────────────────────────
# CRUD — INTERAÇÕES
# ─────────────────────────────────────────────────────────────

def inserir_interacao(visitante_id: int, tipo_acao: str,
                       categoria: str, duracao_seg: int,
                       satisfacao: int) -> int:
    """Registra uma interação do visitante com o tótem."""
    sql = """
        INSERT INTO interacoes (visitante_id, tipo_acao, categoria, duracao_seg, satisfacao)
        VALUES (:visitante_id, :tipo_acao, :categoria, :duracao_seg, :satisfacao)
        RETURNING id INTO :novo_id
    """
    conn = get_connection()
    cursor = conn.cursor()

    novo_id = cursor.var(oracledb.NUMBER)
    cursor.execute(sql, {
        "visitante_id": visitante_id,
        "tipo_acao": tipo_acao,
        "categoria": categoria,
        "duracao_seg": duracao_seg,
        "satisfacao": satisfacao,
        "novo_id": novo_id
    })
    conn.commit()
    cursor.close()
    conn.close()

    return int(novo_id.getvalue()[0])


def listar_interacoes(limit: int = 500) -> list[dict]:
    """Retorna as últimas N interações registradas."""
    sql = """
        SELECT i.id, v.nome, v.perfil, i.tipo_acao, i.categoria,
               i.duracao_seg, i.satisfacao, i.registrado_em
        FROM interacoes i
        JOIN visitantes v ON v.id = i.visitante_id
        ORDER BY i.registrado_em DESC
        FETCH FIRST :limit ROWS ONLY
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(sql, {"limit": limit})
    colunas = [col[0].lower() for col in cursor.description]
    rows = [dict(zip(colunas, row)) for row in cursor.fetchall()]
    cursor.close()
    conn.close()
    return rows


def contar_interacoes_por_categoria() -> list[dict]:
    """Agrupa interações por categoria — usado nos gráficos de analytics."""
    sql = """
        SELECT categoria, COUNT(*) AS total
        FROM interacoes
        GROUP BY categoria
        ORDER BY total DESC
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(sql)
    rows = [{"categoria": r[0], "total": r[1]} for r in cursor.fetchall()]
    cursor.close()
    conn.close()
    return rows


def media_satisfacao_por_tipo() -> list[dict]:
    """Retorna a média de satisfação por tipo de ação."""
    sql = """
        SELECT tipo_acao, ROUND(AVG(satisfacao), 2) AS media_satisfacao
        FROM interacoes
        GROUP BY tipo_acao
        ORDER BY media_satisfacao DESC
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(sql)
    rows = [{"tipo_acao": r[0], "media_satisfacao": r[1]} for r in cursor.fetchall()]
    cursor.close()
    conn.close()
    return rows


# ─────────────────────────────────────────────────────────────
# CRUD — LOGS DO SISTEMA
# ─────────────────────────────────────────────────────────────

def registrar_log(modulo: str, evento: str, nivel: str = "INFO"):
    """Registra um evento do sistema na tabela de logs."""
    sql = """
        INSERT INTO logs_sistema (modulo, evento, nivel)
        VALUES (:modulo, :evento, :nivel)
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(sql, {"modulo": modulo, "evento": evento, "nivel": nivel})
    conn.commit()
    cursor.close()
    conn.close()


# ─────────────────────────────────────────────────────────────
# EXECUÇÃO DIRETA — inicializa as tabelas
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Inicializando banco de dados Oracle...")
    criar_tabelas()
    print("Banco pronto.")
